name: CI

on:
  push:
    branches:
      - master
      - main
  repository_dispatch:
    types: [blog-sync]
  workflow_dispatch:

permissions:
  contents: write

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to gh-pages
        run: |
          remote_addr=$(git remote get-url --push origin)
          commit_info=$(git describe --all --always --long)
          user_name=$(git log -1 --pretty=format:'%an')
          user_email=$(git log -1 --pretty=format:'%ae')
          deploy_branch=gh-pages
          cd website/.vitepress/dist
          git config --global init.defaultBranch "$deploy_branch"
          git init
          git config user.name "$user_name"
          git config user.email "$user_email"
          git add -A
          git commit -m "auto deploy, $commit_info"
          remote_addr=$(echo "$remote_addr" | awk -F'://' '{print $2}')
          remote_addr="https://${user_name}:${{ secrets.BLOG_TOKEN }}@${remote_addr}"
          git remote add origin "$remote_addr"
          git push origin "HEAD:$deploy_branch" --force
